[project]
name = "sym_gpt"
version = "0.0.5"
description = "Use chatGPT and sympy to solve math problems"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["mpmath>=1.3.0", "sympy>=1.13.2"]

[tool.pyright]
venvPath = "."
venv = ".venv"
